services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - ~/.vscode-server:/root/.vscode-server # VS Code server
    ports:
      - "3000:3000"
    command: pnpm run dev # Comando principal para iniciar o desenvolvimento
    environment:
      - CHOKIDAR_USEPOLLING=true # Para melhor compatibilidade em ambientes com volumes
    container_name: portfolio-weblog
    stdin_open: true
    tty: true

volumes:
  node_modules:
